services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: project3_ydqn_user
      POSTGRES_PASSWORD: sbCO6IvVtcCmNLtl3u8iwWIagnMoHnyA
      POSTGRES_DB: project3_ydqn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  book_catalog:
    build: ./book_catalog
    container_name: book_catalog
    environment:
      DATABASE_URL: "postgresql://clanita_sit722_part1_8nso_user:SP8eRKsjZKxIzzx72MOboE9PYOIF7RSL@dpg-crt76s5ds78s73eccdog-a.oregon-postgres.render.com/clanita_sit722_part1_8nso"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  inventory_management:
    build: ./inventory_management
    container_name: inventory_management
    environment:
      DATABASE_URL: "postgresql://clanita_sit722_part1_8nso_user:SP8eRKsjZKxIzzx72MOboE9PYOIF7RSL@dpg-crt76s5ds78s73eccdog-a.oregon-postgres.render.com/clanita_sit722_part1_8nso"
    ports:
      - "8001:8001"
    depends_on:
      - postgres
volumes:
  postgres_data: